language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3

      
# Fake X11 server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


install: pip -q install -e .[tests]

script:
  - pytest -v
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then 
    coverage run tests/test_all.py;
    coveralls; 
    fi
